---
config:
  - name: probe_success
    description: Displays whether or not the probe was a success
    type: gauge
    labels: [service, type]
    sequence:
      - eval_time: 60
        interval: 1
        value: 1
        operation: set
        labels:
          service: proxy
          type: ingress
      - eval_time: 70
        interval: 0
        value: 0
        operation: set
        labels:
          service: proxy
          type: ingress

  - name: probe_duration_seconds
    description: Returns how long the probe took to complete in seconds
    type: gauge
    labels: [service, type]
    sequence:
      - eval_time: 60
        interval: 1
        values: 0.5-0.9
        operation: inc
        labels:
          service: proxy
          type: ingress
      - eval_time: 70
        interval: 1
        values: 0.5-0.9
        operation: dec
        labels:
          service: proxy
          type: ingress
      - eval_time: 1
        interval: 1
        value: 0
        operation: set
        labels:
          service: proxy
          type: ingress

  - name: http_client_requests_seconds_count
    description: Seconds spend in requests
    type: counter
    labels: [service, method, uri]
    sequence:
      - eval_time: 20
        interval: 1
        value: 3
        labels:
          service: hello-world
          method: GET
          uri: /api/v1/service
      - eval_time: 30
        interval: 1
        value: 3
        labels:
          service: hello-world
          method: POST
          uri: /api/v1/service
      - eval_time: 20
        interval: 2
        value: 1
        labels:
          service: hello-world
          method: GET
          uri: /api/v1/service
      - eval_time: 30
        interval: 2
        value: 1
        labels:
          service: hello-world
          method: POST
          uri: /api/v1/service
      - eval_time: 20
        interval: 2
        value: 0
        labels:
          service: hello-world
          method: GET
          uri: /api/v1/service
      - eval_time: 30
        interval: 2
        value: 0
        labels:
          service: hello-world
          method: POST
          uri: /api/v1/service
