global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: generic
    static_configs:
      - targets:
          - prometheus-data-generator:9000
          - linux-node-exporter:9100
          - python-microservice-pyms:8080
          - python-microservice-flask:8080
  - job_name: java-microservice
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - java-microservice:8080
rule_files:
  - /etc/prometheus/rules.yml
