global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus-data-generator
    static_configs:
    - targets: ['prometheus-data-generator:9000']

rule_files:
  - /etc/prometheus/rules.yml
