{
 "title": "Linux Node Exporter",
 "tags": [
  "whitebox",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Vista General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Uso de CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memoria RAM Usada",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{} * 100) / node_memory_MemTotal_bytes{}))"
    }
   ]
  },
  {
   "title": "Uso de la raíz (/)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}))"
    }
   ]
  },
  {
   "title": "Promedio de carga de CPU (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{}) /  count(count(node_cpu_seconds_total{}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Promedio de carga de CPU (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{}) /  count(count(node_cpu_seconds_total{}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Nº de cores de CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{}) by (cpu))"
    }
   ]
  },
  {
   "title": "Ram Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "Tamaño de la raíz (/)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Carga del Sistema 1m avg (load average)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "avg(node_load1{})" }
   ]
  },
  {
   "title": "Tiempo desde arranque",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_time_seconds{} - node_boot_time_seconds{})"
    }
   ]
  },
  {
   "title": "Vista Avanzada",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",}[5m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"user\",}[5m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"iowait\",}[5m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",}[5m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",}[5m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"idle\",}[5m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memoria RAM",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "RAM Total" },
      {
       "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - (node_memory_Cached_bytes{} + node_memory_Buffers_bytes{})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{} + node_memory_Buffers_bytes{}",
       "legendFormat": "RAM Cache + Buffer"
      },
      { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "RAM Free" },
      {
       "expr": "(node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Tráfico de red",
     "type": "graph",
     "description": "Los datos negativos son los datos de salida.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{}[5m])",
       "legendFormat": "Recv {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{}[5m])",
       "legendFormat": "Trans {{device}}"
      }
     ]
    },
    {
     "title": "Espacio de Disco Usado",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{device!~\"rootfs\"} * 100) / node_filesystem_size_bytes{device!~\"rootfs\"})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Estado de los Procesos",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      { "expr": "node_procs_running{}", "legendFormat": "Processes in runnable state" }
     ]
    },
    {
     "title": "Carga del Sistema (load average)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "node_load1{}", "legendFormat": "Load 1m" },
      { "expr": "node_load5{}", "legendFormat": "Load 5m" },
      { "expr": "node_load15{}", "legendFormat": "Load 15m" }
     ]
    },
    {
     "title": "Espacio Disponible del Sistema de Archivos",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{device!~\"rootfs\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "E/S de Disco",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{}[5m])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{}[5m])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    }
   ]
  }
 ]
}